config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admins
  devise_for :voters
  devise_for :candidates, controllers: { registrations: "candidates/registrations" }

  resources :candidacies, only: [:show, :new, :create, :edit, :update]

  namespace :votation do
    resources :sectors, only: [:index], shallow: true do
      resources :candidacies, only: [:index, :show] do
        # resources :votes, only: [:new, :create]
      end
    end
  end

  root to: 'pages#home'
  # get "/vote_confirmation" => "pages#vote_confirmation"



  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/candidacy.rb
class Candidacy < ApplicationRecord
  include ActionView::Helpers::UrlHelper

  belongs_to :candidate
  belongs_to :sector

  has_one_attached :photo
  has_one_attached :document
  has_one_attached :confirmation_letter
  has_one_attached :organization_confirmation_letter
  has_one_attached :autonomus_confirmation_letter
  has_one_attached :election_minute

  has_many :votes

  # after_create :send_confirmation_email

  validates :name, presence: true
  validates :last_name, presence: true
  validates :tax_id_number, presence: true
  validates :tax_id_number, presence: true
  validates :phone, presence: true
  validates :expertise, presence: true
  validates :organization, presence: true
  validates :value_proposition, presence: true
  # validates :photo, presence: true
  # validates :document, presence: true
  # validates :autonomus_confirmation_letter, presence: true
  # validates :confirmation_letter, presence: true
  # validates :organization_confirmation_letter, presence: true
  # validates :election_minute, presence: true
  validates :disclaimer, acceptance: { message: 'Debes aceptar los términos y condiciones' }
  validates :rol, presence: true

  scope :validated, -> { where(validated: true)}
  scope :elected, -> { where(elected: true)}

  def initials
    return if name.blank?

    "#{name} #{last_name}".split(" ").map { |word| word[0] }.reduce(:+)[0..1]
  end


  def cloudinary_url(object)
    return "Sin adjunto" unless object.attachment.present?

    link_to("Ver adjunto", object.service_url, target:"_blank").html_safe
  end

  private

  def send_confirmation_email
    # CandidacyMailer.with(candidacy: self, candidate: self.candidate).confirmation.deliver_now
  end
end

app/controllers/candidacies_controller.rb
class CandidaciesController < ApplicationController

  before_action :set_candidacy, only: %w[show edit update]

  def pundit_user
    current_candidate
  end

  def show
  end

  def new
    @candidacy = Candidacy.new
    authorize @candidacy
  end

  def create
    @candidacy = Candidacy.new(candidacy_params)
    @candidacy.candidate = current_candidate
    authorize @candidacy
    if @candidacy.save
      flash[:notice] = "La información se ha registrado correctamente"
      redirect_to candidacy_path(@candidacy)
    else
      flash.now[:alert] = "Por favor corrija los campos con error e intenta nuevamente"
      render 'new'
    end
  rescue ActiveStorage::IntegrityError => e
    flash.now[:alert] = "Uno o varios de los archivos que intenta subir exceden el tamaño permitido. Por favor elija archivos con menos tamaño e intente nuevamente"
    render 'new'
  end

  def edit
  end

  def update
    if @candidacy.update(candidacy_params)
      flash[:notice] = "La información se ha registrado correctamente"
      redirect_to candidacy_path(@candidacy)
    else
      flash.now[:alert] = "Por favor corrija los campos con error e intenta nuevamente"
      render 'edit'
    end
  rescue ActiveStorage::IntegrityError => e
    flash.now[:alert] = "Uno o varios de los archivos que intenta subir exceden el tamaño permitido. Por favor elija archivos con menos tamaño e intente nuevamente"
    render 'edit'
  end

  private

  def candidacy_params
    params.require(:candidacy).permit(:organization,
                                   :sector_id,
                                   :name,
                                   :last_name,
                                   :tax_id_number,
                                   :place_of_birth,
                                   :place_of_residence,
                                   :address,
                                   :residence_area_type,
                                   :phone,
                                   :secondary_phone,
                                   :email,
                                   :education_level,
                                   :expertise,
                                   :value_proposition,
                                   :disclaimer,
                                   :document,
                                   :confirmation_letter,
                                   :organization_confirmation_letter,
                                   :photo,
                                   :election_minute,
                                   :birthdate,
                                   :rol,
                                   :autonomus_confirmation_letter
                                   )
  end

  def set_candidacy
    @candidacy = authorize Candidacy.find(params[:id])
  end
end

app/controllers/votation/candidacies_controller.rb
class Votation::CandidaciesController < ApplicationController
  skip_after_action :verify_authorized, only: :show
  skip_after_action :verify_policy_scoped, only: :index
  before_action :set_sector, only: [:index]

  def index
    @candidacies = Candidacy.where(sector: @sector).elected.order(:name)
  end

  def show
    @candidacy = Candidacy.find(params[:id])
  end

  private

  def set_sector
    @sector = Sector.find(params[:sector_id])
  end
end

app/controllers/votation/sectors/candidacies_controller.rb
class Votation::Sectors::CandidaciesController < ApplicationController
  skip_after_action :verify_authorized, only: :show
  skip_after_action :verify_policy_scoped, only: :index
  before_action :set_sector, only: :index

  def index
    @candidacies = Candidacy.where(sector: @sector)
  end

  def show
    @candidacy = Candidacy.find(params[:id])
  end

  def set_sector
    @sector = Sector.find(params[:sector_id])
  end
end

app/controllers/votation/sectors_controller.rb
class Votation::SectorsController < ApplicationController

  def pundit_user
    current_voter
  end

  def index
    @sectors = policy_scope([:votation, Sector.all])
  end
end

app/controllers/votation/votes_controller.rb
class Votation::VotesController < ApplicationController

  before_action :set_candidacy, only: %w[new create edit]
  before_action :set_vote, only: %w[edit]
  before_action :set_municipalities, only: %w[new create]
  before_action :set_sectors, only: %w[new create]

  def pundit_user
    current_voter
  end

  def new
    @vote = Vote.new
    authorize @vote
  end

  def edit
    authorize @vote
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.candidacy = @candidacy
    authorize @vote
    if @vote.save
      flash[:notice] = "Su voto se ha registrado con éxito"
      redirect_to vote_confirmation_path
    else
      flash.now[:alert] = "Por favor corrija los campos con error e intente nuevamente"
      render 'new'
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:voter_tid, :voter_phone, :voter_email,
                                 :voter_full_name, :candidacy_id, :municipality_id,
                                 :sector_id, :organization, :document_expedition)
  end

  def set_candidacy
    @candidacy = authorize Candidacy.find(params[:candidacy_id])
    @sector = @candidacy.sector
  end

  def set_vote
    @vote = authorize Vote.find(params[:id])
  end

  def set_municipalities
    @municipalities = Municipality.all.sort_by(&:name)
  end

  def set_sectors
    @sectors = Sector.where(org_type: "Popular").sort_by(&:name)
  end
end

app/views/votation/candidacies/index.html.erb
<div class="candidacy-cards-container">
  <div class="container ">
    <div class="volver-btn d-flex align-items-center">
      <%= render 'shared/go-back-link-sectors'%>
    </div>
    <h1 class="text-center">
      <% if @candidacies.count.positive? %>
        Representantes al Consejo Consultivo Departamental de Mujeres 2020 - 2023.
      <% else %>
        Este sector no cuenta con candidaturas
      <% end %>
    </h1>
    <hr>
    <div class="row">
      <% @candidacies.each do |cand| %>
        <%= link_to votation_candidacy_path(cand), class:"col-xs-12 col-sm-6 card-text-black" do  %>
          <div class="card-candidacy grow">
            <%= cl_image_tag(cand.photo.key, flags: "lossy", fetch_format: :auto)%>
            <div class="card-candidacy-infos">
              <h4><%= "#{cand.name.titleize} #{cand.last_name.titleize}" %></h4>
              <h2><%=  cand.sector.name %></h2>

              <p><%= "#{cand.value_proposition[0..100].capitalize}..." %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/votation/candidacies/show.html.erb
<div class="main-container-vote">
    <div class="volver-btn d-flex align-items-center">
      <%= render 'shared/go-back-link', sector: @candidacy.sector%>
    </div>
  <div class="profile-column">
    <div class="profile-avatar">

      <% if @candidacy.photo.attached? %>
        <%= cl_image_tag(@candidacy.photo.key, secure: true, width: 300, height: 340, class: 'business-show-logo', flags: "lossy",fetch_format: :auto)%>
      <% else %>
        <div class="rounded-lg d-flex justify-content-center align-items-center text-uppercase">
          <p class="font-weight-bold m-0 default-image"><%= @candidacy.initials %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card text-center profile-card sector">
    <h6 class="text-justify font-weight-bold text-center">
      Sector:
    </h6>
    <h6 class="text-justify text-center">
      <%= @candidacy.sector.name %>
    </h6>
  </div>
  <div class="card text-center profile-card organization">
    <h6 class="font-weight-bold text-center">
      Organización:
    </h6>
    <h6 class="text-center">
      <%= @candidacy.organization %>
    </h6>
  </div>
  <div class="card text-center profile-card expertise">
    <div class="card-body">
      <div class="card-title">
        <h1 class="font-weight-bold">
          <%= "#{@candidacy.name.titleize} #{@candidacy.last_name.titleize}" %>
        </h1 class="font-weight-bold">
      </div>
      <div class="card-description text-justify">
        <p>
          <%= @candidacy.expertise %>
        </p>
      </div>
    </div>
  </div>
  <div class="card text-center profile-card value_proposition">
    <div class="card-body">
      <div class="card-title">
        <h6 class="font-weight-bold">
          Propuesta de aporte al Consejo Consultivo Departamental de Mujeres
        </h6 class="font-weight-bold">
      </div>
      <div class="card-description text-justify">
        <p>
          <%= @candidacy.value_proposition %>
        </p>
      </div>
    </div>
  </div>
    <!-- <div class="sticky-xs-btn"> -->
    <div class="sticky-xs-btn d-none">
      <div>
        <%#= link_to "Votar por esta candidata", new_votation_candidacy_vote_path(@candidacy), class:"btn btn-primary btn-lg btn-block btn-vote d-flex justify-content-center align-items-center"  %>
      </div>
    </div>
  </div>
</div>