config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admins
  devise_for :voters
  devise_for :candidates, controllers: { registrations: "candidates/registrations" }

  resources :candidacies, only: [:show, :new, :create, :edit, :update]

  namespace :votation do
    resources :sectors, only: [:index], shallow: true do
      resources :candidacies, only: [:index, :show] do
        # resources :votes, only: [:new, :create]
      end
    end
  end

  root to: 'pages#home'
  # get "/vote_confirmation" => "pages#vote_confirmation"



  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_go-back-link-sectors.erb
<%= link_to votation_sectors_path, class: "text-decoration-none" do %>
  <div class="d-flex btn align-items-center btn-back">
    <%= image_tag "icons/FlechaAtras.svg", class: "back_arrow"%>
    <div class="pl-3">Sectores</div>
  </div>
<% end %>

app/views/shared/_go-back-link.erb
<%= link_to votation_sector_candidacies_path(sector), class: "text-decoration-none" do %>
  <div class="d-flex btn align-items-center btn-back">
    <%= image_tag "icons/FlechaAtras.svg", class: "back_arrow"%>
    <div class="pl-3">Volver a candidatas</div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "unidas-solito.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if entity_signed_in? %>
        <% if current_candidate.candidacy %>
          <%= link_to "Editar Representación", edit_candidacy_path(current_candidate.candidacy), class: "nav-link" %>
        <% else %>
          <%= link_to "Crear Representación", new_candidacy_path, class: "nav-link" %>
        <% end %>
        <%= link_to "Cerrar Sesión", destroy_candidate_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Registrar Representación", new_candidate_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Iniciar Sesión", new_candidate_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>